# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='subject', max_length=200),
            preserve_default=False,
        ),
    ]
